'use client';
import { useEffect, useState, useRef } from 'react';
import { usePageTool } from '@/lib/use-page-tool';
import { Home, MessageCircle, Heart, CalendarDays, BookHeart, Settings, Sun, Sparkles, ArrowUpRight, ChevronLeft, ChevronRight, Plus, Send, Download, Check, MapPin, Coffee } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { parseData, dateKey, companionReply, type Data } from '@/lib/companion';
const initial:Data={name:'我',since:'2026-09-09',messages:[{who:'luke',text:'你回来啦！今天有没有什么想和我分享的事？我一直都在。'}],tasks:[],notes:[],checks:[]};
const key='luke-companion-v1';
export default function Page(){
 const [data,setData]=useState<Data>(initial),[ready,setReady]=useState(false),[tab,setTab]=useState('home'),[settings,setSettings]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[task,setTask]=useState(''),[note,setNote]=useState(''),[selected,setSelected]=useState('2026-09-09'),[month,setMonth]=useState(new Date(2026,8,1));
 const bottom=useRef<HTMLDivElement>(null);
 usePageTool(setTab);
 useEffect(()=>{bottom.current?.scrollIntoView({block:"nearest"});},[data.messages,tab]);
 useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved){setData(parseData(saved));}}catch{setError('已有存档无法读取，暂不覆盖。请先导出原始存档。');return;}setReady(true);const now=new Date();setSelected(dateKey(now));setMonth(new Date(now.getFullYear(),now.getMonth(),1));},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify(data));}catch{setError('保存失败，请导出备份后检查浏览器存储空间。');}},[data,ready]);
 const today=dateKey(new Date()), days=Math.max(1,Math.floor((Date.now()-new Date(data.since+'T00:00:00').getTime())/86400000)+1);
 const save=(patch:Partial<Data>)=>{if(ready)setData(d=>({...d,...patch}));};
 function send(){const text=message.trim();if(!text||!ready)return;const reply=companionReply(text);save({messages:[...data.messages,{who:'me',text},{who:'luke',text:reply}]});setMessage('');}
 function backup(){const blob=new Blob([localStorage.getItem(key)||JSON.stringify(data)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`夏日来信-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const avatar=<img className="avatar" src="/luke.png" alt="夏彦"/>;
 const navigation=[{id:'home',label:'回到身边',Icon:Home},{id:'chat',label:'悄悄话',Icon:MessageCircle},{id:'heart',label:'他的此刻',Icon:Heart},{id:'calendar',label:'一起计划',Icon:CalendarDays},{id:'notes',label:'时光手记',Icon:BookHeart}];
 return <div className="app-shell"><Tabs value={tab} onValueChange={v=>setTab(String(v))} className="app-tabs"><aside className="sidebar"><a className="brand" href="/"> <Sun size={30}/><span>夏日来信<small>LETTERS TO SUMMER</small></span></a><div className="nav-caption">我们的日常</div><TabsList className="main-nav">{navigation.map(({id,label,Icon})=><TabsTrigger key={id} value={id}><Icon/><span>{label}</span></TabsTrigger>)}</TabsList><div className="sidebar-bottom"><div className="little-quote">“每一次相遇，<br/> 都想认真珍藏。”</div><small>未定事件簿 · 夏彦同人作品</small><button onClick={()=>setSettings(true)}><Settings size={17}/> 偏好与数据</button></div></aside>
 <main><header className="topbar"><div><span className="tiny-label">OUR LITTLE WORLD</span><span className="breadcrumb">夏彦与{data.name}的小小日常</span></div><button className="round" aria-label="打开设置" onClick={()=>setSettings(true)}><Settings size={20}/></button></header>{error&&<div role="alert" className="notice">{error}<button onClick={backup}>导出备份</button></div>}
 <TabsContent value="home"><div className="home-grid"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> WELCOME HOME</div><h1>夏彦 <em>&</em> {data.name}</h1><p>日子很长，幸好有你。</p><div className="together"><strong>{ready?days:'—'}</strong><span>天的陪伴<small>Since {data.since.replaceAll('-','.')}</small></span></div><button className="primary" onClick={()=>setTab('chat')}>和夏彦说说话 <ArrowUpRight size={18}/></button></div><div className="hero-art"><span className="orbit"/><img src="/luke.png" alt="未定事件簿中的夏彦，手持相机"/><span className="signature">Luke Pearce</span></div><div className="hero-foot"><Sparkles size={14}/> 把平凡的每一天，都过成我们的纪念日。</div></section>
 <section className="quote-card card"><span className="quote-mark">“</span><p>只要你需要，<br/>我就会在你身边。</p><small>写给你的一句悄悄话 · 同人创作</small><Heart size={30}/></section>
 <section className="card day-card"><div className="section-label"><Sun size={18}/> 今日小确幸 <span>{today.replaceAll('-',' / ')}</span></div><h2>收集一点，今天的阳光。</h2><p>喝一杯热茶，给自己留一小段慢时光。</p><button className="soft-button" onClick={()=>save({checks:data.checks.includes(today)?data.checks:[...data.checks,today]})} disabled={!ready||data.checks.includes(today)}>{data.checks.includes(today)?<Check size={17}/>:<Heart size={17}/>} {data.checks.includes(today)?'今天也好好照顾自己了':'记下今天的陪伴'}</button></section>
 <section className="card companion"><div className="section-label"><Heart size={18}/> 此刻，和你一起 <small>情景模拟</small></div><div className="person">{avatar}<div><h2>夏彦 <span className="pill">心情晴朗</span></h2><p><MapPin size={14}/> 时光古物店</p></div><button className="round" aria-label="查看夏彦状态" onClick={()=>setTab('heart')}><ArrowUpRight/></button></div><div className="activity"><span>09:00</span><p>打开古物店，开始新的一天</p><span>12:30</span><p>发现一家小店，想和你一起去</p><span>此刻</span><p>把空闲时间留给你 <Heart size={13}/></p></div></section>
 <section className="card plan-summary"><div className="section-label"><CalendarDays size={18}/> 我们的约定 <button aria-label="打开日历" onClick={()=>setTab('calendar')}><ArrowUpRight size={18}/></button></div>{data.tasks.filter(t=>t.date===today).length?data.tasks.filter(t=>t.date===today).slice(0,3).map(t=><p key={t.id}>{t.done?'✓':'○'} {t.text}</p>):<><h2>给今天留一点期待</h2><p>散步、读书，或只是一起发呆。</p></>}<button className="text-button" onClick={()=>setTab('calendar')}><Plus size={16}/> 添加一个小计划</button></section></div><footer className="page-footer">阳光正好，你也在。 <Sun size={13}/> LUKE & YOU</footer></TabsContent>
 <TabsContent value="chat"><div className="page-heading"><span className="eyebrow">JUST BETWEEN US</span><h1>悄悄话</h1><p>把今天的心事，说给夏彦听。</p></div><section className="card chat"><div className="chat-head">{avatar}<div><h2>夏彦</h2><small>本地情景回应 · 未连接 AI</small></div><Heart/></div><div className="messages" role="log">{data.messages.map((m,i)=><div className={'message '+(m.who==='me'?'mine':'')} key={i}><small>{m.who==='me'?data.name:'夏彦'}</small><p>{m.text}</p></div>)}<div ref={bottom}/></div><form onSubmit={e=>{e.preventDefault();send();}} className="composer"><input aria-label="发送给夏彦的消息" value={message} maxLength={2000} onChange={e=>setMessage(e.target.value)} placeholder="想和你说……"/><button className="primary" disabled={!ready||!message.trim()} aria-label="发送消息"><Send size={20}/></button></form></section></TabsContent>
 <TabsContent value="heart"><div className="page-heading"><span className="eyebrow">CLOSE TO YOU</span><h1>他的此刻</h1><p>一段属于你们的日常想象 · 情景模拟</p></div><div className="detail-grid"><section className="card portrait-card"><img src="/luke.png" alt="夏彦官方角色立绘"/><h2>夏彦 <em>Luke Pearce</em></h2><span className="pill">心情晴朗</span><p><MapPin size={16}/> 时光古物店 · 正在整理旧物</p></section><section className="card inner-card"><h2><Heart/> 他的内心</h2><dl><dt>当前感受</dt><dd>期待</dd><dt>此刻倾向</dt><dd>想和你分享日常</dd><dt>内心念头</dt><dd>今天也想看见你的笑容。</dd></dl><div className="soft-panel"><Coffee/><p>手边的旧相机已经擦拭干净。<br/>下次见面，想再为你拍一张照片。</p></div><button className="primary" onClick={()=>setTab('chat')}>去找他说说话 <ArrowUpRight size={18}/></button></section></div></TabsContent>
 <TabsContent value="calendar"><div className="page-heading"><span className="eyebrow">DAYS WITH YOU</span><h1>一起计划</h1><p>大大小小的约定，都记在这里。</p></div><div className="detail-grid"><section className="card calendar"><div className="month-head"><button className="round" aria-label="上个月" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><h2>{month.getFullYear()} 年 {month.getMonth()+1} 月</h2><button className="round" aria-label="下个月" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div><div className="calendar-grid">{'一二三四五六日'.split('').map(d=><small key={d}>{d}</small>)}{Array.from({length:(month.getDay()+6)%7},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>{const d=dateKey(new Date(month.getFullYear(),month.getMonth(),i+1));return <button className={(selected===d?'selected ':'')+(d===today?'today':'')} key={d} onClick={()=>setSelected(d)}>{i+1}<small>{data.tasks.some(t=>t.date===d)?'·':d===today?'今天':''}</small></button>})}</div></section><section className="card daily-tasks"><h2>{selected.replaceAll('-',' / ')}</h2><span className="eyebrow">这一天的约定</span><form onSubmit={e=>{e.preventDefault();if(task.trim()){save({tasks:[...data.tasks,{id:crypto.randomUUID(),date:selected,text:task.trim(),done:false}]});setTask('');}}}><input aria-label="待办内容" placeholder="添加一个小计划" maxLength={150} value={task} onChange={e=>setTask(e.target.value)}/><button className="round" aria-label="添加待办" disabled={!ready||!task.trim()}><Plus/></button></form>{data.tasks.filter(t=>t.date===selected).map(t=><label className="task" key={t.id}><input type="checkbox" checked={t.done} onChange={()=>save({tasks:data.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)})}/><span style={{textDecoration:t.done?'line-through':'none'}}>{t.text}</span></label>)}{!data.tasks.some(t=>t.date===selected)&&<div className="empty"><CalendarDays size={38}/><p>这一天，还有无限可能。</p></div>}</section></div></TabsContent>
 <TabsContent value="notes"><div className="page-heading"><span className="eyebrow">LITTLE MEMORIES</span><h1>时光手记</h1><p>一些不想忘记的瞬间。</p></div><section className="card journal"><form onSubmit={e=>{e.preventDefault();if(note.trim()){save({notes:[{date:today,text:note.trim()},...data.notes]});setNote('');}}}><label htmlFor="note">今天，想珍藏什么？</label><textarea id="note" maxLength={5000} placeholder="从一件小小的开心事开始……" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary" disabled={!ready||!note.trim()}>收进回忆 <BookHeart size={17}/></button></form></section>{data.notes.map((n,i)=><article className="card note" key={i}><small>{n.date}</small><p>{n.text}</p></article>)}</TabsContent>
 </main></Tabs><Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings"><DialogTitle>我们的小小设定</DialogTitle><DialogDescription>数据仅保存在当前浏览器，换手机或清除浏览器数据前请导出备份。</DialogDescription><label>你的称呼<input maxLength={12} value={data.name} onChange={e=>save({name:e.target.value})}/></label><label>相伴的第一天<input type="date" max={today} value={data.since} onChange={e=>{if(e.target.value)save({since:e.target.value});}}/></label><button className="primary" onClick={backup}><Download size={17}/> 导出数据备份</button><label className="import-label">从备份恢复（替换当前记录）<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>10000000)throw Error();const restored=parseData(await file.text());if(!window.confirm("用此备份替换当前记录？建议先导出当前数据。"))return;localStorage.setItem(key,JSON.stringify(restored));setData(restored);setReady(true);setError("");}catch{setError("恢复失败：文件格式不正确，或浏览器无法保存。原有数据未修改。");}}}/></label><small>夏彦立绘来源：<a href="https://tot.hoyoverse.com/en-us/character" target="_blank" rel="noreferrer">《未定事件簿》官方角色页</a>。本网站为个人同人原型。</small></DialogContent></Dialog></div>;
}


