'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {complete,completionURL,type ModelConfig} from '@/lib/model';
import {coordinates,fetchWeather,isFresh,weatherAdvice,type Weather,type WeatherConfig} from '@/lib/weather';
import {Sun,CloudRain,Cloud,CloudSnow,CloudLightning,CloudFog,RefreshCw,MapPin,Settings} from 'lucide-react';
export function useConnections(){const [model,setModel]=useState<ModelConfig>({baseUrl:'',model:'',key:''});const [weather,setWeather]=useState<WeatherConfig>({provider:'caiyun',lat:'',lon:'',place:'我的位置',key:'',effects:true});const [loaded,setLoaded]=useState(false);useEffect(()=>{try{const settings=JSON.parse(localStorage.getItem('luke-connections-v1')||'{}');if(settings.model&&typeof settings.model.baseUrl==='string'&&typeof settings.model.model==='string')setModel({...settings.model,key:sessionStorage.getItem('luke-model-key')||''});if(settings.weather&&['caiyun','open-meteo'].includes(settings.weather.provider))setWeather({...settings.weather,key:sessionStorage.getItem('luke-weather-key')||''});}catch{}setLoaded(true);},[]);
 function apply(m:ModelConfig,w:WeatherConfig){if(m.baseUrl)completionURL(m.baseUrl);if(w.lat||w.lon)coordinates(w.lat,w.lon);localStorage.setItem('luke-connections-v1',JSON.stringify({model:{baseUrl:m.baseUrl,model:m.model},weather:{...w,key:undefined}}));sessionStorage.setItem('luke-model-key',m.key);sessionStorage.setItem('luke-weather-key',w.key);setModel(m);setWeather(w);}
 return {model,weather,loaded,apply};}
export function useWeather(config:WeatherConfig,loaded:boolean){const [weather,setWeather]=useState<Weather|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[clock,setClock]=useState(Date.now());const request=useRef<AbortController|null>(null);
 const refresh=useCallback(async()=>{if(!loaded||!config.lat||!config.lon||(config.provider==='caiyun'&&!config.key))return;request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{const result=await fetchWeather(config,AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]));if(!controller.signal.aborted){setWeather(result);setClock(Date.now());}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'天气获取失败，请重试。');}finally{if(!controller.signal.aborted)setLoading(false);}},[config,loaded]);
 useEffect(()=>{setWeather(null);setError('');setLoading(false);void refresh();const tick=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')void refresh();},5*60000);const wake=()=>{if(document.visibilityState==='visible')void refresh();};document.addEventListener('visibilitychange',wake);return()=>{request.current?.abort();clearInterval(tick);document.removeEventListener('visibilitychange',wake);};},[refresh]);
 const fresh=weather&&isFresh(weather,clock)&&!error;return {weather,error,loading,refresh,fresh,context:fresh?`${config.place}：${weather.label}，${weather.temperature}°C。${weatherAdvice(weather)} ${weather.forecast}；${weather.alert}。数据时间 ${new Date(weather.observedAt).toISOString()}`:''};}
export function WeatherCard({state,config,configure}:{state:ReturnType<typeof useWeather>;config:WeatherConfig;configure:()=>void}){const w=state.weather;const Icon=w?({sun:Sun,cloud:Cloud,rain:CloudRain,snow:CloudSnow,storm:CloudLightning,fog:CloudFog})[w.kind]:Cloud;return <section className={'card weather-card '+(config.effects&&state.fresh?'weather-'+w?.kind:'')}><div className="weather-animation" aria-hidden="true"/><div className="section-label"><MapPin size={17}/>{config.place||'我的天气'}<button className="round" aria-label="天气设置" onClick={configure}><Settings size={16}/></button><button className="round" aria-label="刷新天气" onClick={()=>{if(!config.lat||!config.lon||(config.provider==='caiyun'&&!config.key))configure();else void state.refresh();}} disabled={state.loading}><RefreshCw size={16} className={state.loading?'spinning':''}/></button></div>{w?<><div className="weather-reading"><strong>{Math.round(w.temperature)}°</strong><div>{w.label}<small>{state.fresh?'当前天气':'上次天气 · 已过期或更新失败'}</small></div><Icon size={52}/></div><p className="weather-advice">{state.fresh?weatherAdvice(w):'暂时无法确认现在的天气，更新后再看出门提醒。'}</p>{state.fresh&&w.forecast&&<p>{w.forecast}</p>}{state.fresh&&w.alert&&<div className="weather-alert">气象预警：{w.alert}</div>}<small className="weather-source">{w.source} · 数据时间 {new Date(w.observedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</small></>:<div className="weather-empty"><Icon size={36}/><h2>{state.loading?'正在看看窗外的天气…':'今天的天气，也想替你留意'}</h2><p>设置位置和彩云 Token 后，带伞提醒会出现在这里。</p><button className="soft-button" onClick={configure}>连接天气</button></div>}{state.error&&<p role="alert" className="form-feedback">{state.error}</p>}</section>;}
export function ConnectionForm({connections,modelOnly=false,onSaved}:{connections:ReturnType<typeof useConnections>;modelOnly?:boolean;onSaved?:()=>void}){const [m,setM]=useState(connections.model),[w,setW]=useState(connections.weather),[notice,setNotice]=useState(''),[testing,setTesting]=useState(false);const ctrl=useRef<AbortController|null>(null);useEffect(()=>()=>ctrl.current?.abort(),[]);
 async function test(){setTesting(true);setNotice('正在测试模型连接，不发送聊天记录…');ctrl.current=new AbortController();try{await complete(m,[{role:'user',content:'请只回复：连接成功。'}],ctrl.current.signal,1024);setNotice('模型连接成功。记得点击保存连接设置。');}catch(e){setNotice(e instanceof Error?e.message:'连接失败');}finally{setTesting(false);}}
 return <form className="connection-form" onSubmit={e=>{e.preventDefault();try{connections.apply(m,modelOnly?connections.weather:w);setNotice(modelOnly?'模型设置已保存，可开始聊天。':'连接设置已保存。天气将自动刷新。');onSaved?.();}catch(e){setNotice(e instanceof Error?e.message:'保存失败');}}}><h3>模型 API</h3><label>接口地址（Base URL 或完整聊天地址）<input type="url" value={m.baseUrl} onChange={e=>setM({...m,baseUrl:e.target.value})} placeholder="https://你的服务商/v1"/></label><label>模型名称<input value={m.model} maxLength={150} onChange={e=>setM({...m,model:e.target.value})} placeholder="填服务商提供的模型 ID"/></label><label>API Key<input type="password" autoComplete="off" value={m.key} onChange={e=>setM({...m,key:e.target.value})}/></label><button type="button" className="soft-button" onClick={test} disabled={testing}>{testing?'正在测试…':'测试模型连接'}</button><p className="help">支持 Chat Completions 兼容接口。自定义域名需允许跨域。聊天与记忆将发给你选择的服务商；整理长期记忆会额外调用模型。</p>{!modelOnly&&<><h3>天气 · 彩云</h3><label>天气来源<select value={w.provider} onChange={e=>setW({...w,provider:e.target.value as WeatherConfig['provider']})}><option value="caiyun">彩云天气</option><option value="open-meteo">Open-Meteo（免密钥试用）</option></select></label>{w.provider==='caiyun'&&<label>彩云 Token<input type="password" autoComplete="off" value={w.key} onChange={e=>setW({...w,key:e.target.value})}/></label>}<label>地点名称<input maxLength={50} value={w.place} onChange={e=>setW({...w,place:e.target.value})} placeholder="例如：家附近"/></label><div className="coordinate-inputs"><label>纬度<input type="number" step="any" min="-90" max="90" value={w.lat} onChange={e=>setW({...w,lat:e.target.value})}/></label><label>经度<input type="number" step="any" min="-180" max="180" value={w.lon} onChange={e=>setW({...w,lon:e.target.value})}/></label></div><button type="button" className="soft-button" onClick={()=>{if(!navigator.geolocation){setNotice('浏览器不支持定位，请手动输入坐标。');return;}setNotice('正在请求定位…');navigator.geolocation.getCurrentPosition(p=>{setW({...w,lat:p.coords.latitude.toFixed(4),lon:p.coords.longitude.toFixed(4),place:'当前定位'});setNotice('定位完成，请保存设置。');},()=>setNotice('定位未成功，请允许定位或手动填写坐标。'),{timeout:12000,maximumAge:60000});}}><MapPin size={16}/> 使用当前位置</button><label className="inline-label"><input type="checkbox" checked={w.effects} onChange={e=>setW({...w,effects:e.target.checked})}/> 天气小特效</label><p className="help">页面打开时每 5 分钟更新，返回页面时刷新。分钟级降水与预警按彩云套餐权限显示；关闭网页后不会后台提醒。</p></>}<p className="help">密钥只保留在当前标签页会话，刷新仍在，关闭后需重新填写；不会进入聊天备份或云端存档。位置坐标会发给天气服务。</p><button className="primary" disabled={testing}>{modelOnly?'保存并开始聊天':'保存连接设置'}</button><p className="form-feedback" role="status">{notice}</p></form>;}
