'use client';
import {useEffect,useState} from 'react';
import {Hourglass,Play,Pause,RotateCcw} from 'lucide-react';
import type {Data} from '@/lib/companion';
export function Countdown({data,ready,save}:{data:Data;ready:boolean;save:(patch:Partial<Data>|((current:Data)=>Partial<Data>))=>void}){
 const timer=data.countdown??{seconds:300,remainingMs:300000},[now,setNow]=useState(Date.now());
 const end=timer.endsAt,running=end!==undefined;
 useEffect(()=>{if(!ready||end===undefined)return;const update=()=>{const time=Date.now();setNow(time);if(time>=end)save(current=>current.countdown?.endsAt===end?{countdown:{seconds:current.countdown.seconds,remainingMs:0}}:{});};update();const interval=setInterval(update,250);document.addEventListener('visibilitychange',update);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',update);};},[end,ready]);
 const ms=Math.max(0,Math.min(timer.seconds*1000,running?end-now:timer.remainingMs)),seconds=Math.ceil(ms/1000),active=running||ms>0&&ms<timer.seconds*1000;
 function configure(seconds:number){if(Number.isInteger(seconds)&&seconds>=0&&seconds<=86399){save({countdown:{seconds,remainingMs:seconds*1000}});setNow(Date.now());}}
 return <section className="card focus-moment countdown-panel"><h2><Hourglass size={22}/> 倒计时</h2><p role="status">{ms===0&&timer.seconds>0?'时间到啦，手边的事先告一段落吧。':'留一段时间，做你想做的事。'}</p><div className="focus-clock" role="timer" aria-label="倒计时剩余时间">{[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':')}</div><progress aria-label="倒计时进度" max={Math.max(1,timer.seconds*1000)} value={timer.seconds*1000-ms}/><div className="countdown-fields">{([['小时',3600,23],['分钟',60,59],['秒',1,59]] as const).map(([label,multiplier,max])=>{const value=Math.floor(timer.seconds/multiplier)%(label==='小时'?24:60);return <label key={label}>{label}<input aria-label={'倒计时'+label} type="number" min={0} max={max} disabled={!ready||active} value={value} onChange={e=>{const next=Number(e.target.value);if(Number.isInteger(next)&&next>=0&&next<=max)configure(timer.seconds+(next-value)*multiplier);}}/></label>;})}</div><div className="plan-chips">{[5,10,30].map(minutes=><button disabled={!ready||active} key={minutes} onClick={()=>configure(minutes*60)}>{minutes} 分钟</button>)}</div><div className="focus-actions"><button className="primary" disabled={!ready||!timer.seconds} onClick={()=>{const time=Date.now();setNow(time);if(running)save({countdown:{seconds:timer.seconds,remainingMs:Math.max(0,Math.min(timer.seconds*1000,end-time))}});else save({countdown:{...timer,remainingMs:ms||timer.seconds*1000,endsAt:time+(ms||timer.seconds*1000)}});}}>{running?<Pause size={18}/>:<Play size={18}/>} {running?'暂停倒计时':ms===0?'再来一次':active?'继续倒计时':'开始倒计时'}</button><button className="soft-button" disabled={!ready} onClick={()=>{if(active&&!window.confirm('重新设置这次倒计时？'))return;configure(timer.seconds);}}><RotateCcw size={17}/> 重置倒计时</button></div><small>与番茄钟独立运行，不计入专注记录。离开后按时间恢复，不发送后台提醒。</small></section>;
}
