import {weatherCopy} from './home-copy.ts';
import {isAndroid,networkFetch} from './mobile.ts';
export type Weather={temperature:number;label:string;kind:'sun'|'cloud'|'rain'|'snow'|'storm'|'fog';observedAt:number;fetchedAt:number;source:string;forecast:string;rainSoon:boolean;alert:string};
export type WeatherConfig={provider:'caiyun'|'open-meteo';lat:string;lon:string;place:string;key:string;effects:boolean;districtFallback?:boolean;districtEndpoint?:string};
export function coordinates(lat:unknown,lon:unknown){if(lat===''||lon===''||lat===null||lon===null||typeof lat==='boolean'||typeof lon==='boolean')throw Error('请设置地点或经纬度。');const latitude=Number(lat),longitude=Number(lon);if(!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180)throw Error('经纬度超出有效范围。');return {latitude,longitude};}
export function normalizeCaiyun(p:any):Weather{const r=p?.result?.realtime;if(p?.status!=='ok'||r?.status!=='ok'||!Number.isFinite(r.temperature)||typeof r.skycon!=='string'||!Number.isFinite(p.server_time))throw Error('彩云数据无效，请检查 Token 与套餐权限。');const sky=r.skycon;const kind:Weather['kind']=sky.includes('SNOW')?'snow':sky.includes('RAIN')?'rain':sky.includes('THUNDER')?'storm':sky.includes('CLEAR')?'sun':/HAZE|FOG|DUST|SAND/.test(sky)?'fog':'cloud';const labels:Record<string,string>={CLEAR_DAY:'晴',CLEAR_NIGHT:'晴夜',PARTLY_CLOUDY_DAY:'多云',PARTLY_CLOUDY_NIGHT:'多云',CLOUDY:'阴',LIGHT_RAIN:'小雨',MODERATE_RAIN:'中雨',HEAVY_RAIN:'大雨',STORM_RAIN:'暴雨',LIGHT_SNOW:'小雪',MODERATE_SNOW:'中雪',HEAVY_SNOW:'大雪',STORM_SNOW:'暴雪',FOG:'雾',WIND:'大风'};
 const minutely=p.result.minutely;const forecast=minutely?.status==='ok'&&typeof minutely.description==='string'?minutely.description:typeof p.result.forecast_keypoint==='string'?p.result.forecast_keypoint:'';const rainSoon=minutely?.status==='ok'&&Array.isArray(minutely.precipitation_2h)&&minutely.precipitation_2h.slice(0,60).some((n:unknown)=>typeof n==='number'&&n>=0.031);
 return {temperature:r.temperature,label:labels[sky]??(kind==='fog'?'雾霾或沙尘':'天气变化'),kind,observedAt:p.server_time*1000,fetchedAt:Date.now(),source:'彩云天气',forecast:forecast.slice(0,500),rainSoon:Boolean(rainSoon),alert:Array.isArray(p.result.alert?.content)?p.result.alert.content.map((a:any)=>typeof a.title==='string'?a.title:'').filter(Boolean).join('；').slice(0,1000):''};}
export function normalizeMeteo(p:any):Weather{const c=p?.current;if(!Number.isFinite(c?.temperature_2m)||!Number.isInteger(c?.weather_code)||!Number.isFinite(c?.time))throw Error('天气数据不完整。');const code=c.weather_code;const kind:Weather['kind']=code>=95?'storm':[71,73,75,77,85,86].includes(code)?'snow':code>=51?'rain':code>=45?'fog':code>1?'cloud':'sun';return {temperature:c.temperature_2m,kind,label:({sun:'晴',cloud:'多云',rain:'雨',snow:'雪',storm:'雷雨',fog:'雾'})[kind],observedAt:c.time*1000,fetchedAt:Date.now(),source:'Open-Meteo（模型实况）',forecast:'',rainSoon:false,alert:''};}
export function isFresh(w:Weather,now=Date.now()){return now-w.fetchedAt<15*60000&&now-w.observedAt<90*60000&&w.observedAt-now<5*60000;}
export function weatherAdvice(w:Weather,now=new Date()){return weatherCopy(w,now);}
export async function fetchWeather(config:WeatherConfig,signal?:AbortSignal){const {latitude,longitude}=coordinates(config.lat,config.lon);if(isAndroid()){if(config.provider==='caiyun'&&!/^[a-zA-Z0-9_-]{6,256}$/.test(config.key))throw Error('请填写有效的彩云 Token。');const url=config.provider==='caiyun'?`https://api.caiyunapp.com/v2.6/${config.key}/${longitude},${latitude}/weather?alert=true&hourlysteps=12&dailysteps=1`:`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timeformat=unixtime`;const response=await networkFetch(url,{signal});if(!response.ok)throw Error(`天气服务请求失败（${response.status}），请检查网络、Token 和套餐。`);const p=await response.json();return config.provider==='caiyun'?normalizeCaiyun(p):normalizeMeteo(p);}const response=await fetch('/api/weather',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:config.provider,lat:config.lat,lon:config.lon,key:config.key}),signal});const p=await response.json() as any;if(!response.ok)throw Error(p.error||'天气获取失败');return p as Weather;}
