import assert from 'node:assert/strict';
import {finishStudy,studyTime} from '../../lib/study.ts';
import {parseData} from '../../lib/companion.ts';
import {focusStats,rangeFor} from '../../lib/focus-stats.ts';
const start=new Date(2026,7,31,23,50).getTime(),end=new Date(2026,8,1,0,20).getTime();
const base={name:'我',since:'2023-07-08',messages:[],tasks:[],notes:[],checks:[],study:{subject:'数学',startedAt:start}};
assert.deepEqual(parseData(JSON.stringify(base)),base);
const done={...base,...finishStudy(base,start,end)};
assert.equal(done.study,undefined);assert.equal(done.focusLog.length,2);assert.equal(focusStats(done.focusLog,'2026-08-31','2026-08-31').minutes,10);assert.equal(focusStats(done.focusLog,'2026-09-01','2026-09-01').minutes,20);
assert.deepEqual(finishStudy(done,start,end),{});assert.deepEqual(finishStudy(base,start,start-1),{});
assert.deepEqual(parseData(JSON.stringify(done)).focusLog,done.focusLog);
assert.deepEqual(rangeFor('2026-09-09','year'),{from:'2026-01-01',to:'2026-12-31'});
const second={...done,study:{subject:'英语',startedAt:end}},final={...second,...finishStudy(second,end,end+65000)};
assert.equal(focusStats(final.focusLog,'2026-01-01','2026-12-31').categories['数学'],30);assert.equal(studyTime(focusStats(final.focusLog,'2026-01-01','2026-12-31').categories['英语']),'1 分钟');assert.equal(studyTime(60),'60 分钟');
assert.throws(()=>parseData(JSON.stringify({...base,study:{subject:'',startedAt:start}})));
console.log('PASS: restart persistence, exactly-once stop, sub-minute precision, midnight/month split, annual range, math/English totals and validation');
assert.equal(studyTime(0.03798333333333334),'0 分钟');
assert.equal(studyTime(1.99),'1 分钟');
assert.equal(studyTime(0.6+0.6),'1 分钟');
